### ISSUE TITLE
Return statement

### ISSUE THREAD

**Issue by Madave94** [JeromePerleth/Bicubic-Interpolation#5]
Return macht folgendes:

Wenn du hier ankommst nehme den jeweiligen Wert (meist eine variable wie zum Beispiel upscaledimage) und übergebe des Variable - gleichzeitig beendet return damit die Funktion. In deinem Fall würde dein for loop nur eine Iteration durchlaufen bevor mit return die Funktion beendet wird.

Du kannst ja mal `print("hello")` einfügen und schauen wie oft er hello schreibt. zB.

```
# bicubische interpolation
upscaledimage = bikubische_interpolation(img, roi)
print("hello")
return upscaledimag
```

**Comment by JeromePerleth** [comment]
Ja, das war ein Fehler meinerseits, das Return-Statement muss außerhalb des loops stehen, sonst erfolgt lediglich ein Durchlauf mit einmaliger Ausgabe "hello". Ich habe das nun umgeschrieben und insgesamt 225 Ausgaben erhalten, was wesentlich besser aussieht.
